
name: Pytest - ImputeGAP - OPTIMIZATION - 12

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmlpack-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install python3-dev build-essential
        pip install -r requirements.txt
        pip install mypy
        pip install pytest

    - name: Run pytest
      run: |
        python -m pytest ./tests/test_opti_bayesian_cdrec.py
        python -m pytest ./tests/test_opti_bayesian_cdrec_eeg.py
        python -m pytest ./tests/test_opti_bayesian_iim.py
        python -m pytest ./tests/test_opti_bayesian_mrnn.py
        python -m pytest ./tests/test_opti_bayesian_stmvl.py
        python -m pytest ./tests/test_opti_greedy_cdrec.py
        python -m pytest ./tests/test_opti_pso_cdrec.py
        python -m pytest ./tests/test_opti_sh_cdrec.py
        python -m pytest ./tests/test_opti_ray_cdrec_eeg.py