name: Pytest - ImputeGAP - Loading - 12

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmlpack-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install python3-dev build-essential
        pip install --upgrade google protobuf
        pip install -r requirements.txt
        pip install mypy
        pip install pytest


    - name: Run pytest
      run: |
        python -m pytest ./tests/test_loading.py
        python -m pytest ./tests/test_contamination_mcar.py
        python -m pytest ./tests/test_contamination_mp.py
        python -m pytest ./tests/test_contamination_blackout.py
        python -m pytest ./tests/test_contamination_gaussian.py
        python -m pytest ./tests/test_contamination_disjoint.py
        python -m pytest ./tests/test_contamination_overlap.py
        python -m pytest ./tests/test_contamination_distribution.py
        python -m pytest ./tests/test_exception.py
        python -m pytest ./tests/test_benchmarking.py
        python -m pytest ./tests/test_downstream.py